service:
  endpoint: "https://api.example.com"
  api_token: "DEMO_PLACEHOLDER_TOKEN"

database:
  uri: "postgresql://user:placeholder@localhost:5432/app_db"
  password: "SAFE_PLACEHOLDER_VALUE"
  pool_size: 5
